server:
  error:
    whitelabel:
      enabled: false

users:
  selectUsers: "select * from userTable"
  selectUserById: "select * from userTable where id = ?"
  insert: "insert into userTable (name, age) values (?, ?)"
  delete: "delete from userTable where id = ?"
  update: "update userTable set name = ?, age = ? where id = ?"
