server:
  port: 8081

#url, куда будет происходить регистрация микросервисов и другие важные действия
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  packagesToScan: ru.lakeevda.productservice

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost:9091/mem:users
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none