
server:
  port: 8761

eureka:
  instance:
    hostname: localhost
#т.к. это не клиент, то убираем лишние настройки
  client:
    registerWithEureka: false
    fetchRegistry: false
#url, куда будет происходить регисрация микросервисов и другие важные действия
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true